export { default as Error } from './components/Error'
export { default as Login } from './components/Login'
export { default as Player } from './components/Player'
export { default as SpotifyConnect } from './components/SpotifyConnect'
export { default as Welcome } from './components/Welcome'
